__title__ = 'scaffold'
__description__ = '...'
__url__ = 'https://github.com/KIKI007/scaffold'
__version__ = '0.0.1'
__author__ = 'Ziqi Wang'
__author_email__ = 'ziqi.wang@inf.ethz.ch'
__license__ = 'MIT'
__copyright__ = 'Copyright 2023 Ziqi Wang'